import { prisma } from "..";

async function main() {
  try {
    console.log("\n\n🌱 Seeding users genders  to database...");
    await prisma.usersGenders.deleteMany();
    await prisma.usersGenders.createMany({
      data: [
        { id: 1, name: "Masculino" },
        { id: 2, name: "Feminino" },
        { id: 3, name: "Transgênero" },
        { id: 4, name: "Não-binário" },
        { id: 5, name: "Outro" },
      ],
    });

    console.log("\n\n🌱 Seeding vechicles brands to database...");
    await prisma.vehiclesBrands.deleteMany();
    await prisma.vehiclesBrands.createMany({
      data: [
        { id: 1, name: "Audi", icon: "audi.png" },
        { id: 2, name: "BMW", icon: "bmw.png" },
        { id: 3, name: "Chevrolet", icon: "chevrolet.png" },
        { id: 4, name: "Citroën", icon: "citroen.png" },
        { id: 5, name: "Fiat", icon: "fiat.png" },
        { id: 6, name: "Ford", icon: "ford.png" },
        { id: 7, name: "Honda", icon: "honda.png" },
        { id: 8, name: "Hyundai", icon: "hyundai.png" },
        { id: 9, name: "Jeep", icon: "jeep.png" },
        { id: 10, name: "Kia", icon: "kia.png" },
        { id: 11, name: "Mercedes-Benz", icon: "mercedes.png" },
        { id: 12, name: "Mitsubishi", icon: "mitsubishi.png" },
        { id: 13, name: "Nissan", icon: "nissan.png" },
        { id: 14, name: "Peugeot", icon: "peugeot.png" },
        { id: 15, name: "Renault", icon: "renault.png" },
        { id: 16, name: "Toyota", icon: "toyota.png" },
        { id: 17, name: "Volkswagen", icon: "volkswagen.png" },
        { id: 18, name: "Volvo", icon: "volvo.png" },
        { id: 19, name: "Outro", icon: "car.png" },
      ],
    });

    console.log("\n\n🌱 Seeding vechicles names to database...");
    await prisma.vehiclesNames.deleteMany();
    await prisma.vehiclesNames.createMany({
      data: [
        { id: 1, brand_id: 1, name: "A1" },
        { id: 2, brand_id: 1, name: "A3" },
        { id: 3, brand_id: 1, name: "A4" },
        { id: 4, brand_id: 1, name: "A5" },
        { id: 5, brand_id: 1, name: "A6" },
        { id: 6, brand_id: 1, name: "A7" },
        { id: 7, brand_id: 1, name: "A8" },
        { id: 8, brand_id: 1, name: "Q3" },
        { id: 9, brand_id: 1, name: "Q5" },
        { id: 10, brand_id: 1, name: "Q7" },
        { id: 11, brand_id: 1, name: "Q8" },
        { id: 12, brand_id: 1, name: "R8" },
        { id: 13, brand_id: 1, name: "RS3" },
        { id: 14, brand_id: 1, name: "RS4" },
        { id: 15, brand_id: 1, name: "RS5" },
        { id: 16, brand_id: 1, name: "RS6" },
        { id: 17, brand_id: 1, name: "RS7" },
        { id: 18, brand_id: 1, name: "S3" },
        { id: 19, brand_id: 1, name: "S4" },
        { id: 20, brand_id: 1, name: "S5" },
        { id: 21, brand_id: 1, name: "S6" },
        { id: 22, brand_id: 1, name: "S7" },
        { id: 23, brand_id: 1, name: "S8" },
        { id: 24, brand_id: 1, name: "TT" },
        { id: 25, brand_id: 1, name: "TTS" },
        { id: 26, brand_id: 1, name: "Outro" },
        { id: 27, brand_id: 2, name: "Série 1" },
        { id: 28, brand_id: 2, name: "Série 2" },
        { id: 29, brand_id: 2, name: "Série 3" },
        { id: 30, brand_id: 2, name: "Série 4" },
        { id: 31, brand_id: 2, name: "Série 5" },
        { id: 32, brand_id: 2, name: "Série 6" },
        { id: 33, brand_id: 2, name: "Série 7" },
        { id: 34, brand_id: 2, name: "Série 8" },
        { id: 35, brand_id: 2, name: "X1" },
        { id: 36, brand_id: 2, name: "X2" },
        { id: 37, brand_id: 2, name: "X3" },
        { id: 38, brand_id: 2, name: "X4" },
        { id: 39, brand_id: 2, name: "X5" },
        { id: 40, brand_id: 2, name: "X6" },
        { id: 41, brand_id: 2, name: "X7" },
        { id: 42, brand_id: 2, name: "Z4" },
        { id: 43, brand_id: 2, name: "Outro" },
        { id: 44, brand_id: 3, name: "Agile" },
        { id: 45, brand_id: 3, name: "Astra" },
        { id: 46, brand_id: 3, name: "Blazer" },
        { id: 47, brand_id: 3, name: "Bolt" },
        { id: 48, brand_id: 3, name: "Camaro" },
        { id: 49, brand_id: 3, name: "Captiva" },
        { id: 50, brand_id: 3, name: "Celta" },
        { id: 51, brand_id: 3, name: "Classic" },
        { id: 52, brand_id: 3, name: "Cobalt" },
        { id: 53, brand_id: 3, name: "Corsa" },
        { id: 54, brand_id: 3, name: "Cruze" },
        { id: 55, brand_id: 3, name: "Equinox" },
        { id: 56, brand_id: 3, name: "Joy" },
        { id: 57, brand_id: 3, name: "Kadett" },
        { id: 58, brand_id: 3, name: "Malibu" },
        { id: 59, brand_id: 3, name: "Meriva" },
        { id: 60, brand_id: 3, name: "Montana" },
        { id: 61, brand_id: 3, name: "Monza" },
        { id: 62, brand_id: 3, name: "Omega" },
        { id: 63, brand_id: 3, name: "Onix" },
        { id: 64, brand_id: 3, name: "Prisma" },
        { id: 65, brand_id: 3, name: "S10" },
        { id: 66, brand_id: 3, name: "Sonic" },
        { id: 67, brand_id: 3, name: "Spin" },
        { id: 68, brand_id: 3, name: "Tracker" },
        { id: 69, brand_id: 3, name: "Trailblazer" },
        { id: 70, brand_id: 3, name: "Vectra" },
        { id: 71, brand_id: 3, name: "Zafira" },
        { id: 72, brand_id: 3, name: "Outro" },
        { id: 73, brand_id: 4, name: "Aircross" },
        { id: 74, brand_id: 4, name: "Berlingo" },
        { id: 75, brand_id: 4, name: "C3" },
        { id: 76, brand_id: 4, name: "C4" },
        { id: 77, brand_id: 4, name: "C4 Cactus" },
        { id: 78, brand_id: 4, name: "C4 Lounge" },
        { id: 79, brand_id: 4, name: "C4 Picasso" },
        { id: 80, brand_id: 4, name: "C5" },
        { id: 81, brand_id: 4, name: "C5 Aircross" },
        { id: 82, brand_id: 4, name: "C6" },
        { id: 83, brand_id: 4, name: "C8" },
        { id: 84, brand_id: 4, name: "DS3" },
        { id: 85, brand_id: 4, name: "DS4" },
        { id: 86, brand_id: 4, name: "DS5" },
        { id: 87, brand_id: 4, name: "Jumper" },
        { id: 88, brand_id: 4, name: "Jumpy" },
        { id: 89, brand_id: 4, name: "Xsara" },
        { id: 90, brand_id: 4, name: "Xsara Picasso" },
        { id: 91, brand_id: 4, name: "Outro" },
        { id: 92, brand_id: 5, name: "147" },
        { id: 93, brand_id: 5, name: "500" },
        { id: 94, brand_id: 5, name: "500L" },
        { id: 95, brand_id: 5, name: "500X" },
        { id: 96, brand_id: 5, name: "Brava" },
        { id: 97, brand_id: 5, name: "Bravo" },
        { id: 98, brand_id: 5, name: "Cronos" },
        { id: 99, brand_id: 5, name: "Doblò" },
        { id: 100, brand_id: 5, name: "Ducato" },
        { id: 101, brand_id: 5, name: "Elba" },
        { id: 102, brand_id: 5, name: "Fiorino" },
        { id: 103, brand_id: 5, name: "Freemont" },
        { id: 104, brand_id: 5, name: "Grand Siena" },
        { id: 105, brand_id: 5, name: "Idea" },
        { id: 106, brand_id: 5, name: "Linea" },
        { id: 107, brand_id: 5, name: "Marea" },
        { id: 108, brand_id: 5, name: "Mobi" },
        { id: 109, brand_id: 5, name: "Oggi" },
        { id: 110, brand_id: 5, name: "Palio" },
        { id: 111, brand_id: 5, name: "Panorama" },
        { id: 112, brand_id: 5, name: "Punto" },
        { id: 113, brand_id: 5, name: "Siena" },
        { id: 114, brand_id: 5, name: "Stilo" },
        { id: 115, brand_id: 5, name: "Strada" },
        { id: 116, brand_id: 5, name: "Tempra" },
        { id: 117, brand_id: 5, name: "Tipo" },
        { id: 118, brand_id: 5, name: "Toro" },
        { id: 119, brand_id: 5, name: "Uno" },
        { id: 120, brand_id: 5, name: "Outro" },
        { id: 121, brand_id: 6, name: "Courier" },
        { id: 122, brand_id: 6, name: "EcoSport" },
        { id: 123, brand_id: 6, name: "Edge" },
        { id: 124, brand_id: 6, name: "Escort" },
        { id: 125, brand_id: 6, name: "Explorer" },
        { id: 126, brand_id: 6, name: "F-1000" },
        { id: 127, brand_id: 6, name: "F-250" },
        { id: 128, brand_id: 6, name: "F-350" },
        { id: 129, brand_id: 6, name: "F-4000" },
        { id: 130, brand_id: 6, name: "Fiesta" },
        { id: 131, brand_id: 6, name: "Focus" },
        { id: 132, brand_id: 6, name: "Fusion" },
        { id: 133, brand_id: 6, name: "Ka" },
        { id: 134, brand_id: 6, name: "Ka Sedan" },
        { id: 135, brand_id: 6, name: "Mondeo" },
        { id: 136, brand_id: 6, name: "Mustang" },
        { id: 137, brand_id: 6, name: "Pampa" },
        { id: 138, brand_id: 6, name: "Ranger" },
        { id: 139, brand_id: 6, name: "Taurus" },
        { id: 140, brand_id: 6, name: "Verona" },
        { id: 141, brand_id: 6, name: "Versailles" },
        { id: 142, brand_id: 6, name: "Outro" },
        { id: 143, brand_id: 7, name: "Accord" },
        { id: 144, brand_id: 7, name: "City" },
        { id: 145, brand_id: 7, name: "Civic" },
        { id: 146, brand_id: 7, name: "CR-V" },
        { id: 147, brand_id: 7, name: "Fit" },
        { id: 148, brand_id: 7, name: "HR-V" },
        { id: 149, brand_id: 7, name: "WR-V" },
        { id: 150, brand_id: 7, name: "Outro" },
        { id: 151, brand_id: 8, name: "Azera" },
        { id: 152, brand_id: 8, name: "Creta" },
        { id: 153, brand_id: 8, name: "Elantra" },
        { id: 154, brand_id: 8, name: "HB20" },
        { id: 155, brand_id: 8, name: "HB20S" },
        { id: 156, brand_id: 8, name: "HB20X" },
        { id: 157, brand_id: 8, name: "HR" },
        { id: 158, brand_id: 8, name: "i30" },
        { id: 159, brand_id: 8, name: "i30 CW" },
        { id: 160, brand_id: 8, name: "iX35" },
        { id: 161, brand_id: 8, name: "Santa Fe" },
        { id: 162, brand_id: 8, name: "Sonata" },
        { id: 163, brand_id: 8, name: "Tucson" },
        { id: 164, brand_id: 8, name: "Veloster" },
        { id: 165, brand_id: 8, name: "Veracruz" },
        { id: 166, brand_id: 8, name: "Outro" },
        { id: 167, brand_id: 9, name: "Cherokee" },
        { id: 168, brand_id: 9, name: "Compass" },
        { id: 169, brand_id: 9, name: "Grand Cherokee" },
        { id: 170, brand_id: 9, name: "Outro" },
        { id: 171, brand_id: 10, name: "Bongo" },
        { id: 172, brand_id: 10, name: "Cadenza" },
        { id: 173, brand_id: 10, name: "Carnival" },
        { id: 174, brand_id: 10, name: "Cerato" },
        { id: 175, brand_id: 10, name: "Mohave" },
        { id: 176, brand_id: 10, name: "Optima" },
        { id: 177, brand_id: 10, name: "Picanto" },
        { id: 178, brand_id: 10, name: "Sorento" },
        { id: 179, brand_id: 10, name: "Soul" },
        { id: 180, brand_id: 10, name: "Sportage" },
        { id: 181, brand_id: 10, name: "Stinger" },
        { id: 182, brand_id: 10, name: "Outro" },
        { id: 183, brand_id: 11, name: "A 200" },
        { id: 184, brand_id: 11, name: "A 250" },
        { id: 185, brand_id: 11, name: "AMG GT" },
        { id: 186, brand_id: 11, name: "B 200" },
        { id: 187, brand_id: 11, name: "C 180" },
        { id: 188, brand_id: 11, name: "C 200" },
        { id: 189, brand_id: 11, name: "C 250" },
        { id: 190, brand_id: 11, name: "C 300" },
        { id: 191, brand_id: 11, name: "C 63" },
        { id: 192, brand_id: 11, name: "CLA 180" },
        { id: 193, brand_id: 11, name: "CLA 200" },
        { id: 194, brand_id: 11, name: "CLA 250" },
        { id: 195, brand_id: 11, name: "CLA 45" },
        { id: 196, brand_id: 11, name: "CLC 200" },
        { id: 197, brand_id: 11, name: "CLK 320" },
        { id: 198, brand_id: 11, name: "CLS 350" },
        { id: 199, brand_id: 11, name: "CLS 63" },
        { id: 200, brand_id: 11, name: "E 250" },
        { id: 201, brand_id: 11, name: "E 300" },
        { id: 202, brand_id: 11, name: "E 350" },
        { id: 203, brand_id: 11, name: "E 63" },
        { id: 204, brand_id: 11, name: "GLA 200" },
        { id: 205, brand_id: 11, name: "GLA 250" },
        { id: 206, brand_id: 11, name: "GLA 45" },
        { id: 207, brand_id: 11, name: "GLC 250" },
        { id: 208, brand_id: 11, name: "GLC 43" },
        { id: 209, brand_id: 11, name: "GLE 350" },
        { id: 210, brand_id: 11, name: "GLE 400" },
        { id: 211, brand_id: 11, name: "GLE 43" },
        { id: 212, brand_id: 11, name: "GLE 63" },
        { id: 213, brand_id: 11, name: "GLK 220" },
        { id: 214, brand_id: 11, name: "GLK 280" },
        { id: 215, brand_id: 11, name: "GLK 300" },
        { id: 216, brand_id: 11, name: "GLK 350" },
        { id: 217, brand_id: 11, name: "GLS 350" },
        { id: 218, brand_id: 11, name: "GLS 400" },
        { id: 219, brand_id: 11, name: "GLS 63" },
        { id: 220, brand_id: 11, name: "ML 320" },
        { id: 221, brand_id: 11, name: "ML 350" },
        { id: 222, brand_id: 11, name: "ML 400" },
        { id: 223, brand_id: 11, name: "ML 63" },
        { id: 224, brand_id: 11, name: "S 400" },
        { id: 225, brand_id: 11, name: "S 500" },
        { id: 226, brand_id: 11, name: "S 63" },
        { id: 227, brand_id: 11, name: "SL 500" },
        { id: 228, brand_id: 11, name: "SL 63" },
        { id: 229, brand_id: 11, name: "SLK 200" },
        { id: 230, brand_id: 11, name: "SLK 250" },
        { id: 231, brand_id: 11, name: "SLK 350" },
        { id: 232, brand_id: 11, name: "SLK 55" },
        { id: 233, brand_id: 11, name: "SLS 63" },
        { id: 234, brand_id: 11, name: "Outro" },
        { id: 235, brand_id: 12, name: "ASX" },
        { id: 236, brand_id: 12, name: "Eclipse Cross" },
        { id: 237, brand_id: 12, name: "L200" },
        { id: 238, brand_id: 12, name: "Lancer" },
        { id: 239, brand_id: 12, name: "Outlander" },
        { id: 240, brand_id: 12, name: "Pajero" },
        { id: 241, brand_id: 12, name: "Pajero Dakar" },
        { id: 242, brand_id: 12, name: "Pajero Full" },
        { id: 243, brand_id: 12, name: "Pajero Sport" },
        { id: 244, brand_id: 12, name: "Outro" },
        { id: 245, brand_id: 13, name: "350Z" },
        { id: 246, brand_id: 13, name: "370Z" },
        { id: 247, brand_id: 13, name: "Frontier" },
        { id: 248, brand_id: 13, name: "GT-R" },
        { id: 249, brand_id: 13, name: "Kicks" },
        { id: 250, brand_id: 13, name: "Leaf" },
        { id: 251, brand_id: 13, name: "March" },
        { id: 252, brand_id: 13, name: "Sentra" },
        { id: 253, brand_id: 13, name: "Tiida" },
        { id: 254, brand_id: 13, name: "Versa" },
        { id: 255, brand_id: 13, name: "X-Trail" },
        { id: 256, brand_id: 13, name: "Outro" },
        { id: 257, brand_id: 14, name: "2008" },
        { id: 258, brand_id: 14, name: "207" },
        { id: 259, brand_id: 14, name: "208" },
        { id: 260, brand_id: 14, name: "3008" },
        { id: 261, brand_id: 14, name: "307" },
        { id: 262, brand_id: 14, name: "308" },
        { id: 263, brand_id: 14, name: "408" },
        { id: 264, brand_id: 14, name: "5008" },
        { id: 265, brand_id: 14, name: "508" },
        { id: 266, brand_id: 14, name: "Boxer" },
        { id: 267, brand_id: 14, name: "Expert" },
        { id: 268, brand_id: 14, name: "Hoggar" },
        { id: 269, brand_id: 14, name: "Partner" },
        { id: 270, brand_id: 14, name: "RCZ" },
        { id: 271, brand_id: 14, name: "Outro" },
        { id: 272, brand_id: 15, name: "Captur" },
        { id: 273, brand_id: 15, name: "Clio" },
        { id: 274, brand_id: 15, name: "Duster" },
        { id: 275, brand_id: 15, name: "Fluence" },
        { id: 276, brand_id: 15, name: "Kangoo" },
        { id: 277, brand_id: 15, name: "Kwid" },
        { id: 278, brand_id: 15, name: "Logan" },
        { id: 279, brand_id: 15, name: "Master" },
        { id: 280, brand_id: 15, name: "Megane" },
        { id: 281, brand_id: 15, name: "Sandero" },
        { id: 282, brand_id: 15, name: "Scenic" },
        { id: 283, brand_id: 15, name: "Symbol" },
        { id: 284, brand_id: 15, name: "Outro" },
        { id: 285, brand_id: 16, name: "Amarok" },
        { id: 286, brand_id: 16, name: "Crossfox" },
        { id: 287, brand_id: 16, name: "Fox" },
        { id: 288, brand_id: 16, name: "Fusca" },
        { id: 289, brand_id: 16, name: "Gol" },
        { id: 290, brand_id: 16, name: "Golf" },
        { id: 291, brand_id: 16, name: "Jetta" },
        { id: 292, brand_id: 16, name: "Kombi" },
        { id: 293, brand_id: 16, name: "Parati" },
        { id: 294, brand_id: 16, name: "Passat" },
        { id: 295, brand_id: 16, name: "Polo" },
        { id: 296, brand_id: 16, name: "Saveiro" },
        { id: 297, brand_id: 16, name: "Space Cross" },
        { id: 298, brand_id: 16, name: "SpaceFox" },
        { id: 299, brand_id: 16, name: "T-Cross" },
        { id: 300, brand_id: 16, name: "Tiguan" },
        { id: 301, brand_id: 16, name: "Touareg" },
        { id: 302, brand_id: 16, name: "Up!" },
        { id: 303, brand_id: 16, name: "Virtus" },
        { id: 304, brand_id: 16, name: "Voyage" },
        { id: 305, brand_id: 16, name: "Outro" },
        { id: 306, brand_id: 17, name: "300C" },
        { id: 307, brand_id: 17, name: "300M" },
        { id: 308, brand_id: 17, name: "Caravan" },
        { id: 309, brand_id: 17, name: "Cirrus" },
        { id: 310, brand_id: 17, name: "Concorde" },
        { id: 311, brand_id: 17, name: "Crossfire" },
        { id: 312, brand_id: 17, name: "Neon" },
        { id: 313, brand_id: 17, name: "New Yorker" },
        { id: 314, brand_id: 17, name: "PT Cruiser" },
        { id: 315, brand_id: 17, name: "Sebring" },
        { id: 316, brand_id: 17, name: "Stratus" },
        { id: 317, brand_id: 17, name: "Town & Country" },
        { id: 318, brand_id: 17, name: "Voyager" },
        { id: 319, brand_id: 17, name: "Outro" },
        { id: 320, brand_id: 18, name: "Dakota" },
        { id: 321, brand_id: 18, name: "Durango" },
        { id: 322, brand_id: 18, name: "Journey" },
        { id: 323, brand_id: 18, name: "RAM" },
        { id: 324, brand_id: 18, name: "Outro" },
        { id: 325, brand_id: 19, name: "Defender" },
        { id: 326, brand_id: 19, name: "Discovery" },
        { id: 327, brand_id: 19, name: "Discovery Sport" },
        { id: 328, brand_id: 19, name: "Freelander" },
        { id: 329, brand_id: 19, name: "Range Rover" },
        { id: 330, brand_id: 19, name: "Range Rover Evoque" },
        { id: 331, brand_id: 19, name: "Range Rover Sport" },
        { id: 332, brand_id: 19, name: "Range Rover Velar" },
        { id: 333, brand_id: 19, name: "Outro" },
      ],
    });

    console.log("\n\n🌱 Seeding business categories to database...");
    await prisma.businessCategories.deleteMany();
    await prisma.businessCategories.createMany({
      data: [
        { id: 1, name: "Acessórios" },
        { id: 2, name: "Câmbio" },
        { id: 3, name: "Elétrico" },
        { id: 4, name: "Fluidos" },
        { id: 5, name: "Funilaria e Pintura" },
        { id: 6, name: "Lavagem" },
        { id: 7, name: "Mecânico" },
        { id: 8, name: "Pneus" },
        { id: 9, name: "Suspensão" },
        { id: 10, name: "Vidros" },
        { id: 11, name: "Outros" },
      ],
    });

    console.log("\n\n🌱 Seeding business types to database...");
    await prisma.businessServices.deleteMany();
    await prisma.businessServices.createMany({
      data: [
        // Acessórios
        { id: 1, category_id: 1, name: "Calotas" },
        { id: 2, category_id: 1, name: "Carregadores" },
        { id: 3, category_id: 1, name: "Suportes" },
        { id: 4, category_id: 1, name: "Outros" },

        // Câmbio
        { id: 5, category_id: 2, name: "Retifica" },
        { id: 6, category_id: 2, name: "Revisão" },
        { id: 7, category_id: 2, name: "Troca de fluido" },
        { id: 8, category_id: 2, name: "Outros" },

        // Elétrico
        { id: 9, category_id: 3, name: "Bateria" },
        { id: 10, category_id: 3, name: "Lâmpadas" },
        { id: 11, category_id: 3, name: "Revisão" },
        { id: 12, category_id: 3, name: "Vidros" },
        { id: 13, category_id: 3, name: "Outros" },

        // Fluidos
        { id: 14, category_id: 4, name: "Arrefecimento" },
        { id: 15, category_id: 4, name: "Freio" },
        { id: 16, category_id: 4, name: "Óleo" },
        { id: 17, category_id: 4, name: "Outros" },

        // Funilaria e Pintura
        { id: 18, category_id: 5, name: "Funilaria" },
        { id: 19, category_id: 5, name: "Pintura" },
        { id: 20, category_id: 5, name: "Outros" },

        // Lavagem
        { id: 21, category_id: 6, name: "Completa" },
        { id: 22, category_id: 6, name: "Simples" },
        { id: 23, category_id: 6, name: "Outros" },

        // Mecânico
        { id: 24, category_id: 7, name: "Alinhamento" },
        { id: 25, category_id: 7, name: "Balanceamento" },
        { id: 26, category_id: 7, name: "Correia dentada" },
        { id: 27, category_id: 7, name: "Embreagem" },
        { id: 28, category_id: 7, name: "Escapamento" },
        { id: 29, category_id: 7, name: "Freio" },
        { id: 30, category_id: 7, name: "Injeção eletrônica" },
        { id: 31, category_id: 7, name: "Motor" },
        { id: 32, category_id: 7, name: "Revisão" },
        { id: 33, category_id: 7, name: "Suspensão" },
        { id: 34, category_id: 7, name: "Outros" },

        // Pneus
        { id: 35, category_id: 8, name: "Alinhamento" },
        { id: 36, category_id: 8, name: "Balanceamento" },
        { id: 37, category_id: 8, name: "Troca" },
        { id: 38, category_id: 8, name: "Reparos" },
        { id: 39, category_id: 8, name: "Outros" },

        // Suspensão
        { id: 40, category_id: 9, name: "Amortecedor" },
        { id: 41, category_id: 9, name: "Molas" },
        { id: 42, category_id: 9, name: "Outros" },

        // Vidros
        { id: 43, category_id: 10, name: "Reparo" },
        { id: 44, category_id: 10, name: "Troca" },
        { id: 45, category_id: 10, name: "Outros" },

        // Outros
        { id: 46, category_id: 11, name: "Outros" },
      ],
    });

    console.log("\n\n🌱 Seeding Logs type to database...");
    await prisma.logsTypes.deleteMany();
    await prisma.logsTypes.createMany({
      data: [
        { id: 1, name: "Alert" },
        { id: 2, name: "Error" },
        { id: 3, name: "Info" },
        { id: 4, name: "Success" },
        { id: 5, name: "Warning" },
      ],
    });

    console.log("\n\n🌱 Seeding insurance companies to database...");
    await prisma.insuranceCompanies.deleteMany();
    await prisma.insuranceCompanies.createMany({
      data: [
        {id: 1, name: "Azul Seguros", created_at: new Date()},
        {id: 2, name: "Bradesco Seguros", created_at: new Date()},
        {id: 3, name: "Caixa Seguradora", created_at: new Date()},
        {id: 4, name: "HDI Seguros", created_at: new Date()},
        {id: 5, name: "Itaú Seguros", created_at: new Date()},
        {id: 6, name: "Liberty Seguros", created_at: new Date()},
        {id: 7, name: "Mapfre Seguros", created_at: new Date()},
        {id: 8, name: "Porto Seguro", created_at: new Date()},
        {id: 9, name: "SulAmérica Seguros", created_at: new Date()},
        {id: 10, name: "Tokio Marine Seguradora", created_at: new Date()},
        {id: 11, name: "Outro", created_at: new Date()},
        {id: 12, name: "Não tenho seguro", created_at: new Date()},
      ]
    });

    console.log("\n\n🌱 Seeding car insurance types to database...");
    await prisma.insuranceTypes.deleteMany();
    await prisma.insuranceTypes.createMany({
      data: [
        {id: 1, name: "Acidentes com proprietário", created_at: new Date()},
        {id: 2, name: "Acidentes com terceiros", created_at: new Date()},
        {id: 3, name: "Assistência 24 horas", created_at: new Date()},
        {id: 4, name: "Carro reserva", created_at: new Date()},
        {id: 5, name: "Danos a terceiros", created_at: new Date()},
        {id: 6, name: "Furto e roubo", created_at: new Date()},
        {id: 7, name: "Incêndio", created_at: new Date()},
        {id: 8, name: "Outro", created_at: new Date()},
      ]
    });

    console.log("\n\n🌱 Seeding document types to database...");
    await prisma.documentsTypes.deleteMany();
    await prisma.documentsTypes.createMany({
      data: [
        {id: 1, name: "image", created_at: new Date()},
        {id: 2, name: "application", created_at: new Date()},
        {id: 3, name: "video", created_at: new Date()},
        {id: 4, name: "audio", created_at: new Date()},
      ]
    });


  } catch (error) {
    throw new Error(error);
  }
}

main()
  .then(() => {
    prisma.$disconnect();
  })
  .catch((error) => {
    console.log("Cannot insert data to database: ", error);
  });
